# Generated by Django 3.1.7 on 2021-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210329_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
